trustyai-explainability/trustyai-service-operator

README.md, api/v1alpha1/trustyaiservice_types.go, artifacts/examples/deploy-operator.yaml, artifacts/examples/example-trustyai.yaml, config/crd/bases/trustyai.opendatahub.io.trustyai.opendatahub.io_trustyaiservices.yaml
Namespace no longer needed in the CR.
TrustyAI service namespace is taken from where the CR is deployed.
Closes #11 .
=> Remove namespace from CR

README.md, api/v1alpha1/trustyaiservice_types.go, artifacts/examples/example-config-map.yaml, config/crd/bases/trustyai.opendatahub.io.trustyai.opendatahub.io_trustyaiservices.yaml, controllers/trustyaiservice_controller.go, controllers/utils.go, main.go
[RHODS-9182](https://issues.redhat.com/browse/RHODS-9182) / #23 
Configure the operator to use custom images by creating a `ConfigMap` in the operator's namespace. 
The operator only checks the `ConfigMap` at deployment, so changes made afterward won't trigger a redeployment of services.
Example ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: trustyai-service-operator-config
data:
trustyaiServiceImageName: 'quay.io/mycustomrepo/mycustomimage'
trustyaiServiceImageTag: 'v1.0.0'
```
=> Use ConfigMap to customise TrustyAI operator's service image

config/base/kustomization.yaml, config/manager/manager.yaml
The operator's deployment would create an unused namespace, this PR removes it.
The deployment namespace would be specified either by a KfDef or by directly applying the operator deployment in a specific namespace.
=> Remove operator's unused namespace

README.md, config/base/kustomization.yaml, config/base/params.env, config/manager/kustomization.yaml
Operator KFDef can now specify image name and tag:
```yaml
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
name: trustyai-service-operator
namespace: opendatahub
spec:
applications:
- kustomizeConfig:
repoRef:
name: manifests
path: config
parameters:
- name: trustyaiServiceImageName
value: NEW_IMAGE_NAME
- name: trustyaiServiceImageTag
value: NEW_IMAGE_TAG
name: trustyai-service-operator
repos:
- name: manifests
uri: https://github.com/trustyai-explainability/trustyai-service-operator/tarball/main
version: v1.0.0
```
=> Add parameterized configmap to specify service image

tests/scripts/install.sh
With new kfdef parameters, sed's need to match on placeholder values to avoid match conflicts
=> Update CI Seds

tests/scripts/install.sh
This will revert to default image values if triggered by a non-trustyai-service-operator PR (i.e., from the main Openshift CI repo)
=> Refine conditionals in CI install script

config/base/kustomization.yaml, controllers/constants.go, controllers/monitor.go, controllers/suite_test.go, controllers/trustyaiservice_controller.go
Change TrustyAI operator and resources `app.kubernetes.io/part-of` to `trustyai` in order to match the ODH v2 TrustyAI component name
=> feat: Change `part-of` label to match ODH v2 component name

config/rbac/role.yaml, controllers/constants.go, controllers/inference_services.go, controllers/suite_test.go, controllers/trustyaiservice_controller.go, main.go, tests/crds/monitoring.coreos.com_servicemonitors.yaml, tests/crds/route_crd.yaml, tests/crds/serving.kserve.io_servingruntimes.yaml
This PR adds a periodic requeueing of the reconciler to check that the CR's `ServingRuntimes` are properly configured, in the scenario where they are recreated after the `InferenceService`.
Also add missing CRDs for local tests.
=> feat: Add reconcile delay

go.mod, go.sum
Upgrade `google.golang.org/grpc@1.55.0` to `google.golang.org/grpc@1.56.3` in order to fix CVE-2023-44487.
Result of Snyk
```
$ snyk test
✔ Tested 695 dependencies for known issues, no vulnerable paths found.
```
=> Upgrade google.golang.org/grpc

Makefile, config/rbac/role.yaml, controllers/constants.go, controllers/events.go, controllers/finalizers.go, controllers/inference_services.go, controllers/monitor.go, controllers/statuses.go, controllers/storage.go, controllers/suite_test.go, controllers/trustyaiservice_controller.go, main.go
Add Kubernetes events to the `TrustyAIService`:
- `PVCCreated`
- `InferenceServiceConfigured`
- `ServiceMonitorCreated`
The Ready condition has also been refactored, in order to be set only at the end of a successful (for the Readiness criteria) reconcilition.
By moving the Readiness check as the last step of the reconciliation, this PR also addresses https://github.com/trustyai-explainability/trustyai-service-operator/issues/76.
=> Implement lifecycle events.

config/rbac/kustomization.yaml
This PR adds the `TrustyAIService` viewer and editor roles to the operator's default deployments.
=> Deploy TrustyAI editor and viewer roles

controllers/constants.go, controllers/deployment.go, controllers/inference_services.go, controllers/route.go, controllers/route_test.go, controllers/statuses.go, controllers/statuses_test.go, controllers/storage.go, controllers/suite_test.go, controllers/trustyaiservice_controller.go
This PR introduces the `Available` condition.
This condition is set to `True` if the PVC, Route and Deployment are ready.
The definition of ready is:
- PVC bound
- Route is admitted
- Deployment is Available and with expected number of replicas
The `Available` condition would be `False` otherwise.
`InferenceServices` do not have a bearing in `Available` and whether they are present or not will be reflected in the `InferenceServicesPresent` condition.
The readiness status checks are moved to the `reconcileStatuses` method and performed together, rather than at each component's (PVC, Route, etc) check.
=> Add Available condition and checks

config/crd/bases/trustyai.opendatahub.io_trustyaiservices.yaml, controllers/service_accounts.go, controllers/service_accounts_test.go, controllers/suite_test.go
Fixes [RHOAIENG-2135](https://issues.redhat.com/browse/RHOAIENG-2135)
When creating multiple `TrustyAIServices`, endpoint authentication will fail.
Steps to reproduce using the CLI:
Assuming:
- A TrustyAI operator already deployed
- `$CLUSTER` is your cluster address.
- A `$TOKEN` as `export TOKEN=$(oc whoami -t)`
- No models are required to reproduce this
Create a namespace `test`. 
Add a first `TrustyAIService` in this namespace , using, for instance (`trustyai-test.yaml`)
```
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: TrustyAIService
metadata:
name: trustyai-service
spec:
storage:
format: "PVC"
folder: "/inputs"
size: "1Gi"
data:
filename: "data.csv"
format: "CSV"
metrics:
schedule: "5s"
```
and
```
oc apply -f trustyai-test.yaml -n test
```
Try the external endpoint:
```
curl …
```
=> [RHOAIENG-2135] Add unique ClusterRoleBinding names

config/rbac/auth_proxy_service.yaml
Correct pod port for the operator metrics service.
=> Change metrics service pod target to 8080

controllers/templates/service/deployment.tmpl.yaml
See [RHOAIENG-2918](https://issues.redhat.com/browse/RHOAIENG-2918).
This PR removes `/metrics` from the skip-auth.
=> RHOAIENG-2918: Remove /metrics from skip-auth

Makefile, controllers/deployment.go, controllers/deployment_test.go, controllers/oauth.go, controllers/service_accounts.go, controllers/services.go, controllers/templates/service/deployment.tmpl.yaml, controllers/templates/service/service-internal.tmpl.yaml, controllers/templates/service/service-tls.tmpl.yaml, controllers/trustyaiservice_controller.go, controllers/version.go
See [RHOAIENG-2419](https://issues.redhat.com/browse/RHOAIENG-2419).
TrustyAI resources are deployed with a version label of `0.1.0` by default.
This PR enables consistent `version` labels.
=> RHOAIENG-2419: Add version information to resources

controllers/templates/service/route.tmpl.yaml
See [RHOAIENG-6275](https://issues.redhat.com/browse/RHOAIENG-6275) and https://github.com/trustyai-explainability/trustyai-service-operator/issues/233.
Edge TLS for the external route is now managed by OpenShift.
Connection is reencrypted to the OAuth proxy, since that pod does not accept unencrypted connections.
=> RHOAIENG-6275: Change route termination to reencrypt

config/overlays/odh/kustomization.yaml, config/overlays/odh/params.env, config/overlays/rhoai/kustomization.yaml
[RHOAIENG-6342](https://issues.redhat.com/browse/RHOAIENG-6342).
Add overlays specifically for ODH and RHOAI.
=> RHOAIENG-6342: Add ODH and RHOAI overlays

config/crd/bases/trustyai.opendatahub.io_trustyaiservices.yaml, config/rbac/role.yaml, controllers/constants.go, controllers/templates/service/deployment.tmpl.yaml, controllers/templates/service/service-internal.tmpl.yaml
Add support for HTTP and HTTPS at the TrustyAI internal service level using OpenShift Serving Certificates
=> Add internal service TLS

config/overlays/testing/image-pull-policy.yaml, config/overlays/testing/kustomization.yaml
This overlay is intended to use in TrustyAI development and testing.
This PR adds an `ImagePullPolicy: Always` to the operator image for testing purposes.
=> feat: Add testing overlay

Dockerfile, go.mod, go.sum
See [RHOAIENG-8648](https://issues.redhat.com/browse/RHOAIENG-8648).
=> RHOAIENG-8648: Update Go builder and toolset to 1.21

controllers/certificates.go, controllers/constants.go, controllers/inference_services.go, controllers/utils.go
Adds support for mounting TrustyAI internal's service serving certificates on the ModelMesh container.
Changes the TrustyAI payload processor to match the TLS certificate's CN and SAN.
See [RHOAIENG-4963](https://issues.redhat.com/browse/RHOAIENG-4963).
=> feat: Add TLS certificate mount on ModelMesh

config/base/kustomization.yaml, config/base/params.env, controllers/config_maps.go, controllers/constants.go, controllers/inference_services.go
See [RHOAIENG-10687](https://issues.redhat.com/browse/RHOAIENG-10687).
This PR adds a configuration option to the TrustyAI operator `ConfigMap` to enable/disable KServe Serverless patching.
By default, KServe Serverless will be disabled, meaning KServe `InferenceServices` will not be patched.
To enable it, the following `ConfigMap` can be deployed in the operator's namespace:
```yaml
apiVersion: v1
data:
kServeServerless: enabled
oauthProxyImage: quay.io/openshift/origin-oauth-proxy:4.14.0
trustyaiOperatorImage: quay.io/ruimvieira/trustyai-service-operator:...
trustyaiServiceImage: quay.io/ruimvieira/trustyai-service:...
kind: ConfigMap
metadata:
labels:
app.kubernetes.io/part-of: trustyai
name: trustyai-service-operator-config
```
=> feat: ConfigMap key to disable KServe Serverless configuration

controllers/deployment.go, controllers/secrets.go, controllers/templates/service/deployment.tmpl.yaml
This PR adds support for custom certificates for the TrustyAI service database connection.
Certificates are stored in a Kubernetes `Secret` named `${TRUSTY_SERVICE_NAME}-db-tls` and must include at least a `tls.crt` key.
- If the certificate is present, it will be mounted on the TrustyAI pod and passed to the JDBC connection string
- If the certificate is _not_ present, a connection without TLS will be created (this is same behaviour as previously)
The secret must be created prior to TrustyAI as the operator will not watch for database TLS secrets creation.
=> feat: Add support for custom certificates in database connection

controllers/inference_services.go, controllers/utils.go
- Add TLS endpoint for ModelMesh payload processors.
- Keep non-TLS endpoint for KServe Serverless (disabled by default)
Only to be merged after https://github.com/opendatahub-io/modelmesh/pull/65 is merged.
=> Add TLS endpoint for ModelMesh payload processors.

controllers/deployment_test.go, controllers/secrets.go, controllers/suite_test.go, controllers/templates/service/deployment.tmpl.yaml
See [RHOAIENG-10214](https://issues.redhat.com/browse/RHOAIENG-10214).
Add `databaseName` field to the database configuration.
=> feat: Add support for custom DB names

tests/Dockerfile, tests/Makefile, tests/README.md
Change Dockerfile in order to clone and run the tests from trustyai-tests.
=> [CI] Run tests from trustyai-tests

Dockerfile.driver, cmd/lmes_driver/main.go, controllers/lmes/constants.go, controllers/lmes/driver/driver.go, controllers/lmes/driver/driver_test.go, controllers/lmes/lmevaljob_controller.go
The driver periodically update the LMEvalJob.Status.Message field with the outputs from the lm-eval. The message pattern the driver captures is like `Running text generation:  81%|`. Then users can use this information to check the progress of the job.
=> feat: Driver updates job's status periodically

cmd/lmes_driver/main.go, controllers/lmes/constants.go, controllers/lmes/driver/driver.go, controllers/lmes/driver/driver_test.go, controllers/lmes/lmevaljob_controller.go, controllers/lmes/lmevaljob_controller_test.go
Added a new feature in the LMES driver to detect the available devices by using the PyTorch API. This feature can be disabled by passing the `--detect-device false` option.
fix: #297
=> feat: add device detection in lmes driver

config/overlays/odh/params.env, config/rbac/role.yaml, controllers/destination_rule.go, controllers/inference_services.go, controllers/templates/service/destination-rule.tmpl.yaml, controllers/trustyaiservice_controller.go
This PR adds a `DestinationRule` to the `TrustyAIService` namespace when configuring a KServe `InferenceService` inside the ServiceMesh, so that the Inference Logger is able to send payloads to the TAS (outside the mesh).
=> Add KServe destination rule for Inference Services in the ServiceMesh

config/rbac/auth_proxy_service.yaml
Refer to [RHOAIENG-14321](https://issues.redhat.com/browse/RHOAIENG-14321).
Fix target port in operator's service metrics.
=> RHOAIENG-14321: Fix operator metrics service target port

controllers/lmes/lmevaljob_controller.go, controllers/lmes/lmevaljob_controller_test.go
Refers to [RHOAIENG-13846](https://issues.redhat.com/browse/RHOAIENG-13846).
This PR removes the hardcoded job's pod user id, so that it can use the id automatically assigned by OpenShift.
=> RHOAIENG-13846: Remove hardcoded job's user ID

config/base/params.env, config/overlays/rhoai/params.env
Refers to [RHOAIENG-11109](https://issues.redhat.com/browse/RHOAIENG-11109).
Re-enable the KServe serverless support by default.
=> RHOAIENG-11109: Enable KServe serverless in the rhoai overlay

config/rbac/role.yaml, controllers/inference_services.go, controllers/templates/service/virtual-service.tmpl.yaml, controllers/trustyaiservice_controller.go, controllers/utils.go, controllers/virtual_service.go
* Create `VirtualService`s automatically for Inference Logger traffic
* Rename Inference Logger endpoint to conform with destination rules and virtual services
=> Support for VirtualServices for InferenceLogger traffic

controllers/lmes/config.go, controllers/lmes/driver/driver_test.go, controllers/lmes/lmevaljob_controller.go, controllers/lmes/lmevaljob_controller_test.go
Refactors createPod other related methods to static functions because I need to create PodSet for Kueue integration using those functions
=> Refactor some lmesreconcile methods

Dockerfile.lmes-job
remove BAM-related packages and patch.
=> tidy: clean up lmes-job image

api/lmes/v1alpha1/lmevaljob_types.go, api/lmes/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml, controllers/lmes/config.go, controllers/lmes/constants.go, controllers/lmes/lmevaljob_controller.go, controllers/lmes/lmevaljob_controller_test.go
Refers to [RHOAIENG-14773](https://issues.redhat.com/browse/RHOAIENG-14773).
This PR changes the field `batchSize` from `int` to `string` in order to support the values `auto` and `auto:N`.
Validation is performed by the controller for the following scenarios:
* `batchSize="n"`, assuming `n` is a positive integer it will be used, otherwise use the default batch size
* `batchSize="auto"`, `auto` will be used
* `batchSize="auto:n"`, if `n` is a positive integer `auto:n` will be used and the maximum batch size will be ignored (`n` will be the maximum batch size). If `n` is invalid (negative, or not a `int`), `auto:maxBatchSize` will be used.
* `batchSize="n"`, (where `n > maxBatchSize`) maximum batch size will be used
This PR also lower the default batch size from `8` to `1`.
=> RHOAIENG-14773: Change batchSize to string in order to support "auto" and "auto:N"

.github/workflows/smoke.yaml, tests/smoke/test_smoke.sh
=> fix(test): Allow smoke test to pass

config/rbac/auth_proxy_service.yaml
Reverts the operator's metrics service target port to `https`.
=> fix(RHOAIENG-14321): Revert metrics service target port to https

config/overlays/odh-kueue/kustomization.yaml, config/overlays/odh-kueue/params.env, config/overlays/odh-kueue/patch.yaml
Add `odh-kueue` overlay with job manager enabled for Kueue support.
=> feat(lmeval): Add overlay for Kueue support

controllers/job_mgr/README.md, controllers/job_mgr/job_mgr_controller.go
1. Resolves #368 
1. Add none nodeLabels example to README
=> fix(lmeval): Disallow empty nodeAffinity

config/base/params.env, config/overlays/odh-kueue/params.env, config/overlays/odh/params.env, config/overlays/rhoai/params.env, controllers/lmes/config.go, controllers/lmes/constants.go, controllers/lmes/lmevaljob_controller.go, controllers/lmes/lmevaljob_controller_test.go
Add feature flag to the operator to enable the `allowOnline` and `allowCodeExecution` CR flags.
The operator feature will not set the LMEval Job deployment mode. This flag is purely to set (at the controller level) if an LMEval Job is _allowed_ to use the online and code execution flags.
Refer to [RHOAIENG-16816](https://issues.redhat.com/browse/RHOAIENG-16816).
=> feat(lmeval): Add operator online and execution feature flag

controllers/lmes/lmevaljob_controller.go, controllers/lmes/lmevaljob_controller_test.go
The LMEval Job CR allows to set env vars directly from the CR.
This PR disables setting protected vars (i.e. related to offline and code execution), thus overriding the offline/no execution CR settings.
Refer [RHOAIENG-16885](https://issues.redhat.com/browse/RHOAIENG-16885).
=> feat(lmeval): Filter protected env vars set from CR directly

controllers/lmes/lmevaljob_controller.go, controllers/lmes/lmevaljob_controller_test.go
Use only `unitxt` catalogs when in offline mode.
Refer to [RHOAIENG-17761](https://issues.redhat.com/browse/RHOAIENG-17761).
=> fix: Use only local unitxt catalogs when in offline mode

Dockerfile.lmes-job
lm-evaluation-path to be made consistent with metrics path (https://github.com/opendatahub-io/lm-evaluation-harness/pull/16). Previously it was `/opt/app-root/src/lm-evaluation-harness` and this PR makes it `/opt/app-root/src`.
=> fix(lmeval): Make lm-evaluation-harness source path consistent

config/manager/manager.yaml
Increased from `cpu:500m,memory:128Mi` to `cpu:900m,memory:700Mi`
Refer to [RHOAIENG-18226](https://issues.redhat.com/browse/RHOAIENG-18226).
=> fix: Increase resource limits for the TrustyAI operator

controllers/lmes/lmevaljob_controller.go
When running the pod exec to call the driver APIs, it's better to specify the name of the main container. Otherwise, it would cause errors when there are multiple running containers.
=> fix: Run PodExec against the main container

cmd/lmes_driver/main.go, controllers/lmes/config.go, controllers/lmes/constants.go, controllers/lmes/driver/driver.go, controllers/lmes/driver/driver_test.go, controllers/lmes/lmevaljob_controller.go, controllers/lmes/lmevaljob_controller_test.go
Originally, the LMES driver used a Unix domain socket to serve the APIs which are used by the LMES controller to retrieve the job status. Switch to a container port to allow other containers in the same job pod to access the APIs as well.
=> feat(LMES): Switch LMES driver to a container port

controllers/gorch/configmap.go, controllers/gorch/deployment.go
Refer to [RHOAIENG-20116](https://issues.redhat.com/browse/RHOAIENG-20116).
Orchestrator's image configuration is now correctly retrieved from a ConfigMap in the user namespace called `${orch-name}-config`.
=> fix(RHOAIENG-20116): Use correct ConfigMap for orchestrator image config

config/base/kustomization.yaml
Kustomize is not replacing the operator's deployment image (as specified in `params.env`) correctly, since the final Kustomize name was not being used.
Refer to: [RHOAIENG-21663](https://issues.redhat.com/browse/RHOAIENG-21663)
=> fix: Use final Kustomize deployment name for operator image

api/gorch/v1alpha1/guardrailsorchestrator_types.go, api/gorch/v1alpha1/zz_generated.deepcopy.go, config/base/params.env, config/crd/bases/trustyai.opendatahub.io_guardrailsorchestrators.yaml, config/overlays/odh/params.env, config/overlays/rhoai/params.env, controllers/gorch/constants.go, controllers/gorch/deployment.go, controllers/gorch/guardrailsorchestrator_controller_test.go, controllers/gorch/templates/deployment.tmpl.yaml, controllers/gorch/templates/service.tmpl.yaml
This PR addresses [RHOAIENG-23547](https://issues.redhat.com/browse/RHOAIENG-23547) by making the following changes:
* Adds two new boolean flags to the GORCH CR to enable the regex detectors and vLLM gateway sidecars separately: `regexDetectors` and `vllmGateway`
* Adds the regex detectors and vLLM gateway image tags to `params.env`
* Reads the image references to both from the `trustyai-service-config` configmap
* Updates tests to reflect changes
=> RHOAIENG-23547: Decouple vllm-gateway and regex detector

config/component_metadata.yaml
- Component metadata now pointing to tags on upstream
- Added component metadata for the RegEx detector and vLLM gateway
=> chore: Update component metadata
