- controllers/trustyaiservice_controller.go
[RHODS-8862](https://issues.redhat.com/browse/RHODS-8862) / #1
> Add owner references

- api/v1alpha1/trustyaiservice_types.go
- config/crd/bases/trustyai.opendatahub.io.trustyai.opendatahub.io_trustyaiservices.yaml
Remove namespace from CR TrustyAI service deployments.
> Remove namespace from CR

- controllers/trustyaiservice_controller.go
> Fix resource ownership

- controllers/trustyaiservice_controller.go
[RHODS-9279](https://issues.redhat.com/browse/RHODS-9279) /  #36
> Fix CR status and conditions updates

- config/rbac/role.yaml
- controllers/trustyaiservice_controller.go
Route `watch` permission missing.
> Add correct permission for Routes

- config/manager/manager.yaml
> Update pod security context

- controllers/deployment.go
- controllers/suite_test.go
- controllers/trustyaiservice_controller.go
Remove Prometheus port from ServiceMonitor and Pod annotations
> Remove Prometheus port

- tests/scripts/install.sh
See https://github.com/trustyai-explainability/trustyai-explainability/pull/383
> Custom image support for local CI

- tests/scripts/install.sh
This will fail until https://github.com/trustyai-explainability/trustyai-explainability/pull/386 is merged
> Update CI for new operator image spec

- controllers/constants.go
- controllers/statuses.go
- controllers/trustyaiservice_controller.go
Add a `RouteAvailable` status with `RouteNotFound` and `RouteFound` reasons.
> feat: Add Route status

- config/base/params.env
Release 1.10.3 including 2023-39325 fixes.
> Release 1.10.3

- config/base/params.env
> Release 1.12.0

- config/rbac/kustomization.yaml
- config/rbac/trustyaiservice_editor_role.yaml
- config/rbac/trustyaiservice_viewer_role.yaml
Aggregate `TrustyAIService` viewer and editor roles to respective main ones.
> Aggregate roles

- controllers/deployment_test.go
- controllers/route_test.go
- controllers/storage_test.go
- controllers/suite_test.go
- go.mod
- go.sum
Add more unit tests, specifically for route and storage reconciliation.
> Add route and storage tests

- .github/workflows/lint-yaml.yaml
- .yamllint.yaml
- README.md
- config/base/kustomization.yaml
- config/base/manager_auth_proxy_patch.yaml
- config/base/manager_config_patch.yaml
- config/base/params.yaml
- config/crd/bases/trustyai.opendatahub.io.trustyai.opendatahub.io_trustyaiservices.yaml
- config/crd/kustomization.yaml
- config/crd/kustomizeconfig.yaml
- config/crd/patches/webhook_in_trustyaiservices.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/manifests/kustomization.yaml
- config/prometheus/kustomization.yaml
- config/rbac/auth_proxy_client_clusterrole.yaml
- config/rbac/auth_proxy_role.yaml
- config/rbac/auth_proxy_role_binding.yaml
- config/rbac/auth_proxy_service.yaml
- config/rbac/kustomization.yaml
- config/rbac/leader_election_role.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/role.yaml
- config/rbac/role_binding.yaml
- config/rbac/trustyaiservice_editor_role.yaml
- config/rbac/trustyaiservice_viewer_role.yaml
- config/scorecard/bases/config.yaml
- config/scorecard/kustomization.yaml
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/olm.config.yaml
Add YAML linting CI to manifests
> Add YAML linting workflow and fix YAML formatting

- controllers/deployment.go
- controllers/deployment_test.go
- controllers/oauth.go
- controllers/templates/parser.go
- controllers/templates/service/deployment.tmpl.yaml
- controllers/templates/service/service-tls.tmpl.yaml
See [RHOAIENG-2304](https://issues.redhat.com/browse/RHOAIENG-2304).
> [RHOAIENG-2304] Refactor deployment to use templates

- .github/workflows/controller-tests.yaml
- controllers/route.go
- controllers/route_test.go
- controllers/statuses_test.go
- controllers/templates/service/route.tmpl.yaml
See [RHOAIENG-3118](https://issues.redhat.com/browse/RHOAIENG-3118).
> RHOAIENG-3118: Replace route object with template

- config/base/params.env
- controllers/deployment_test.go
- controllers/templates/service/deployment.tmpl.yaml
- controllers/templates/service/service-tls.tmpl.yaml
- Add CA location to OAuth proxy
- Mount annotated secret for oauth
- Use annotated secret for oauth
> Properly mount CA bundle ConfigMap into OAuth proxy

- .github/workflows/smoke.yaml
- tests/smoke/manifests/trustyai-cr.yaml
- tests/smoke/test_smoke.sh
Add smoke test to the operator.
This PR sets the infrastructure to replicate and use the operator's unit tests in a Kubernetes cluster, provisioned for each PR.
> Add GH Actions smoke tests to the operator 

- .github/workflows/controller-tests.yaml
- Makefile
- go.mod
Fixes [RHOAIENG-4870](https://issues.redhat.com/browse/RHOAIENG-4870).
> RHOAIENG-4870: Update sdk-go version

- .github/workflows/build-and-push.yaml
This is a temporary revert for release v1.19 until we reproduce the results locally
> Revert multi-arch temporarily

- controllers/inference_services.go
See [RHOAIENG-10500](https://issues.redhat.com/browse/RHOAIENG-10500).
Disable `InferenceService` configuration when its in `RawDeployment` mode.
> fix: Skip InferenceService patching for KServe RawDeployment [RHOAIENG-10500]

- .github/workflows/build-and-push.yaml
Add LMES drive image build to GHA.
> feat: Add LMES driver build to GHA

- Dockerfile.lmes-job
- patch/lmes/models.patch
Add Dockerfile for LMES job image and the needed files
related: #274
> feat: Add Dockerfile for LMES job image

- .github/workflows/build-and-push.yaml
Add LMES job image build to GHA.
> RHOAIENG-11969: Add job image build

- config/overlays/odh/params.env
- config/overlays/rhoai/kustomization.yaml
- config/overlays/rhoai/params.env
See [RHOAIENG-12274](https://issues.redhat.com/browse/RHOAIENG-12274).
> RHOAIENG-12274: Update operator's overlays

- Dockerfile.lmes-job
update the LMES job's Dockerfile to include the
`openai` package.
fix: #291
> fix: add the `openai` package into the lmes job image

- Dockerfile.lmes-job
Use midstream's `release-0.4.5` branch for upstream releases.
> Checkout current LMEH release from midstream

- controllers/lmes/lmevaljob_controller.go
- controllers/lmes/lmevaljob_controller_test.go
Refer to [RHOAIENG-16200](https://issues.redhat.com/browse/RHOAIENG-16200)
> feat(lmeval): Add offline mode as default

- controllers/lmes/lmevaljob_controller.go
- controllers/lmes/lmevaljob_controller_test.go
Refer to [RHOAIENG-16203](https://issues.redhat.com/browse/RHOAIENG-16203)
> feat(lmeval): Disable remote code execution

- Dockerfile.lmes-job
Bundle evaluate's metrics for offline usage.
> feat(lmeval): Add offline metrics to LMEval job image

- go.mod
- go.sum
Refer [RHOAIENG-18309](https://issues.redhat.com/browse/RHOAIENG-18309).
> fix(CVE-2024-45337): Enforce x/crypto 0.31.0

- .github/workflows/build-and-push.yaml
This PR corrects the container manifest name for the orchestrator GHA
> fix(guardrails): Add correct orchestrator container manifest name

- Dockerfile.orchestrator
Now includes fetching midstream orchestrator repository.
> fix(guardrails): Fix orchestrator container manifest

- .github/workflows/smoke.yaml
- config/base/kustomization.yaml
- config/crd/kustomization.yaml
- config/manager/manager.yaml
- config/overlays/lmes/kustomization.yaml
- config/overlays/odh-kueue/kustomization.yaml
- config/overlays/testing/kustomization.yaml
- tests/smoke/test_smoke.sh
Remove warnings for Kustomize v5.
Refer to [RHOAIENG-6720](https://issues.redhat.com/browse/RHOAIENG-6720).
> fix(RHOAIENG-6720): Remove Kustomize v5 deprecation warnings

- config/component_metadata.yaml
Update component metadata with new post-release branches.
> chore(RHOAIENG-15495):  Update main component metadata with correct branches

- controllers/gorch/guardrailsorchestrator_controller_test.go
- controllers/gorch/suite_test.go
- Test two instances in the same namespace
- Test instances in different namespaces
Tests verify proper resource creation and cleanup for each instance
> feat( RHOAIENG-20330): Update GuardrailsOrchestrator unit tests

- config/base/kustomization.yaml
- config/crd/kustomization.yaml
- config/manager/manager.yaml
- config/overlays/lmes/kustomization.yaml
- config/overlays/odh-kueue/kustomization.yaml
- config/overlays/testing/kustomization.yaml
> Revert "fix(RHOAIENG-6720): Remove Kustomize v5 deprecation warnings (#425)"
